//irrelevant right now

function basic() {
    //words found thanks to
    
    var sfa = [ "Validate your fucking ideas.",
               "Keep your investors in the fucking loop.",
               "Fucking measure your KPI's.",
               "Email your fucking mentors.",
               "Make something fucking useful.",
               "Take fucking breaks.",
               "Don't fucking give up.",
               "Keep fucking trying.",
               "Talk to fucking people.",
               "Ask for fucking advice.",
               "Take all advice like a fucking grain of salt.",
               "Don't let mentors change your fucking ideas.",
               "Fucking test everything.",
               "Don't act like a fucking startup.",
               "Go fucking workout.",
               "Take care of your fucking self.",
               "Eat fucking right.",
               "Stay fucking self-funded as long as possible.",
               "Chase the fucking vision, not the money.",
               "Ask. Don't fucking tell.",
               "Make every fucking detail perfect.",
               "Limit the fucking number of details to perfect.",
               "Don’t fucking worry about failure.",
               "Know what your fucking product is.",
               "Know who your fucking customers are.",
               "Know how you're going to make fucking money.",
               "Take fucking risks.",
               "Fix your fucking mistakes.",
               "Have fucking lawyers.",
               "Carefully choose your fucking investors.",
               "Know how to fucking scale.",
               "Let your designers be fucking creative.",
               "Have fucking developers.",
               "Don't worry about your fucking salary.",
               "Refine your fucking skills.",
               "Just fucking launch.",
               "Work with people who push you to the fucking extreme.",
               "Spend time and money on fucking marketing.",
               "Fucking brand yourself.",
               "Connect with fucking influencers.",
               "Think outside the fucking box.",
               "Nothing is fucking impossible.",
               // Submitted Advice
               "Fire your un-talented fucking partners.",
               "Don't fuck up.",
               "Sweat equity is the fucking best startup capital.",
               "Don't fuck with your fucking product... Unless it's a rubber doll.",
               "Don't fuck your fucking team.",
               "Choose your startup partners fucking wisely.",
               "Be fucking original.",
               "Keep personal life and work life fucking seperate.",
               "Don't trust all the fucking advice.",
               "Get out there and shake some fucking hands.",
               "Don't ever fucking give up! (Unless it's fucking time to give up...)",
               "Be fucking honest.",
               "Being an entrepreneur is like suicide: requires balls and everything to lose. Fucking do it, anyway.",
               "Stop worrying about fucking investors. Worry about customers.",
               "Keep your communications fucking professional.",
               "Sales cure every fucking thing.",
               "Don't spend the whole day here! Go build your fucking product!",
               "DON'T BE A FUCKING IDIOT.",
               "Have a fucking purpose!",
               "Don't fucking run out of money!",
               "Don't fuck with your investors.",
               "Don't look for cofounders at fucking startup events.",
               "Stop making fucking excuses. Just fucking do it!",
               "Fucking do it now. Don't procrastinate.",
               "WORK FUCKING HARDER!",
               "Know Who You're Fucking With!",
               "Solve the fucking problem.",
               "Don't bend over while fucking negotiating.",
               "Hire some fucking designers!",
               "Don't be fucking cheap. Quality over quantity.",
               "Reject bad fucking ideas and protocols.",
               "Don't fucking recruit employees with bad attitude.",
               "Pay your fucking debts.",
               "Choose your investors fucking wisely.",
               "Men or Women. Pay them fucking equal.",
               "Don't be fucking afraid to use Google.com",
               "Do not fucking borrow or loan money from your boyfriend/girlfriend.",
               "Fucking use Minimalist Web Design and adhere to KISS Principle.",
               "Ask yourself this from day one: Do I want to do business or I just want to fuck around?!",
               "Find out what people fucking need, not what people think they might fucking want.",
               "Spend a good time finding a good fucking partner.",
               "Never fucking underestimate your competitors.",
               "Be fucking patient.",
               "Start integrating your fucking SaaS Apps.",
               "FUCK THE LOGIC.",
               "Don't worry about fucking clients. No, wait. Don't fucking worry about clients. Fucking worry about grammar.",
               "Make fucking money.",
               "Don't fucking be afraid of failure.",
               "Talk to your fucking customers.",
               "An entrepreneur is willing to challenge fucking tradition, in order to discover new and better ways to accomplish their goals and dreams.",
               "Don't hire for academic fucking excellence, hire for proven ability to execute.",
               "Stop fucking procrastinating.",
               "Be a fucking LEADER!",
               "Decisions: Make the fucking hard right over the easy wrong EVERY fucking time!",
               "Never stop fucking learning.",
               "Be a master of your own fucking destiny.",
               "Don't be fucking ignorant!",
               "Lead from the fucking front.",
               "Quit fucking talking and start fucking doing.",
               "Just fucking sell!",
               "Stop fucking around, Start the fuck up.",
               "Do the fucking work.",
               "Get a domain, and a fucking email with it.",
               "Be humble. Keep a fucking cool head all the time!",
               "Just fucking do what has not been done before",
               "Reply to fucking emails!",
               "Focus on your revenue and not fucking features.",
               "Stop fucking complaining. Get shit done.",
               "Hire people who are fucking smarter than you!",
               "Know your fucking competitors!",
               "Make it fucking responsive!",
               
               ];
    
    var who = sfa[Math.round(Math.random()*(sfa.length-1))];
    
    document.getElementById('advices').innerHTML = '<div>' + who + '</div>'
    
}